/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/lgernido/local"
#define EXEC_PREFIX "/home/lgernido/local"
#define BINDIR "/home/lgernido/local/bin"
#define SBINDIR "/home/lgernido/local/sbin"
#define LIBEXECDIR "/home/lgernido/local/libexec"
#define DATAROOTDIR "/home/lgernido/local/share"
#define DATADIR "/home/lgernido/local/share"
#define SYSCONFDIR "/home/lgernido/local/etc"
#define SHAREDSTATEDIR "/home/lgernido/local/com"
#define LOCALSTATEDIR "/home/lgernido/local/var"
#define RUNSTATEDIR "/home/lgernido/local/var/run"
#define INCLUDEDIR "/home/lgernido/local/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/lgernido/local/share/doc/gettext"
#define INFODIR "/home/lgernido/local/share/info"
#define HTMLDIR "/home/lgernido/local/share/doc/gettext"
#define DVIDIR "/home/lgernido/local/share/doc/gettext"
#define PDFDIR "/home/lgernido/local/share/doc/gettext"
#define PSDIR "/home/lgernido/local/share/doc/gettext"
#define LIBDIR "/home/lgernido/local/lib"
#define LISPDIR "/home/lgernido/local/share/emacs/site-lisp"
#define LOCALEDIR "/home/lgernido/local/share/locale"
#define MANDIR "/home/lgernido/local/share/man"
#define PKGDATADIR "/home/lgernido/local/share/gettext"
#define PKGINCLUDEDIR "/home/lgernido/local/include/gettext-tools"
#define PKGLIBDIR "/home/lgernido/local/lib/gettext-tools"
#define PKGLIBEXECDIR "/home/lgernido/local/libexec/gettext-tools"
