services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: redis
    expose:
      - 6379
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code/backend
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    env_file:
      - .env
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - default

  # elasticsearch:
  #   image: bitnami/elasticsearch:latest
  #   environment:
  #     - ELASTICSEARCH_HEAP_SIZE=1024m
  #     - discovery.type=single-node
  #   volumes:
  #     - elasticsearch_data:/bitnami/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - default

  # logstash:
  #   image: bitnami/logstash:latest
  #   environment:
  #     - LOGSTASH_ELASTICSEARCH_URL=elasticsearch
  #     - LOGSTASH_ELASTICSEARCH_PORT_NUMBER=9200
  #   volumes:
  #     - ./configuration/logstash/logstash.conf:/opt/bitnami/logstash/pipeline/logstash.conf
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - default

  # kibana:
  #   image: bitnami/kibana:latest
  #   environment:
  #     - KIBANA_ELASTICSEARCH_URL=elasticsearch
  #     - KIBANA_ELASTICSEARCH_PORT_NUMBER=9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - default

volumes:
  postgres_data:
  # elasticsearch_data:


networks:
  default:
    driver: bridge

