services:
  db:
    image: postgres:13.4
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=superpongdb
      - POSTGRES_USER=superpong
      - POSTGRES_PASSWORD=gnoprepus
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - default

  redis:
    image: redis:7.4
    container_name: redis
    expose:
      - 6379
    networks:
      - default

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code/backend
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - default
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./ssl:/etc/ssl
    depends_on:
      - backend
    networks:
      - default
    env_file:
      .env

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
