version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DEBUG=1

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
