# Generated by Django 4.2.16 on 2024-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
