# Generated by Django 4.2.17 on 2025-01-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
