# Generated by Django 4.2.17 on 2024-12-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_name',
            field=models.CharField(default='default_room', max_length=255),
        ),
    ]
