# Generated by Django 4.2.17 on 2024-12-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='privateRoom',
            field=models.BooleanField(default=False),
        ),
    ]
