# Generated by Django 4.2.17 on 2024-12-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_privateroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='points_limit',
            field=models.IntegerField(default=5),
        ),
    ]
