# Generated by Django 4.2.17 on 2024-12-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_points_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
