# Generated by Django 4.2.17 on 2024-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_room_player1_ready_room_player2_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1_color',
            field=models.CharField(default='color-player-default', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='player2_color',
            field=models.CharField(default='color-player-default', max_length=50),
        ),
    ]
