# Generated by Django 4.2.16 on 2024-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_blocked_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
