# Generated by Django 4.2.16 on 2024-11-22 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_friendship_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_user',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
