# Generated by Django 4.2.16 on 2024-11-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_remove_profile_blocked_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, to='users.social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='friends_user',
            field=models.ManyToManyField(blank=True, to='users.social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to=settings.AUTH_USER_MODEL),
        ),
    ]
