# Generated by Django 4.2.16 on 2024-11-23 13:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_social_avatar_alter_social_blocked_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', upload_to=users.models.avatar_upload_to),
        ),
    ]
