# Generated by Django 4.2.16 on 2024-11-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_social_blocked_user_alter_social_friends_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, to='users.social'),
        ),
        migrations.AlterField(
            model_name='social',
            name='friends_user',
            field=models.ManyToManyField(blank=True, to='users.social'),
        ),
    ]
