# Generated by Django 4.2.16 on 2024-11-27 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_alter_social_blocked_user_alter_social_friends_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='friends_user',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
