# Generated by Django 4.2.17 on 2024-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_social_blocked_user_alter_social_friends_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='user42',
            field=models.BooleanField(default=False),
        ),
    ]
